### ISSUE TITLE
Unable to run sample codes

### ISSUE THREAD

**Issue by anking** [webex/webex-js-sdk#1143] opened 2019-04-23 15:05 UTC
when trying to execute "npm run samples:serve" bunch of errors like this will showup:

ERROR in ./packages/node_modules/@ciscospark/spark-core/src/lib/storage/make-spark-store.js 107:4
Module parse failed: Unexpected character '@' (107:4)
You may need an appropriate loader to handle this file type.
|     }

**Comment by tahanson-cisco** [comment] 2019-04-23 15:28
@anking , can you provide your version information (npm, node, etc)?

**Comment by anking** [comment] 2019-04-23 15:42
NPM: 6.5.0
Node: 8.15.1

Globally installed packages
c:\dev>npm list -g --dept

+-- @angular/cli@6.2.4
+-- create-react-app@2.0.2
+-- node-gyp@3.8.0
+-- npm@6.5.0
+-- typescript@3.1.1
`-- windows-build-tools@5.1.0

**Comment by taymoork2** [comment] 2019-04-30 00:22
I'm not able to reproduce. I downloaded a zip of the repo and ran `npm install` on it and didn't get any errors when I served the samples.

Here are some steps I suggest you should take.

1. Build, run `npm run build && npm run samples:build`
if that doesn't work
2. Delete `node_modules` folder and run `npm install && npm rebuild`
and if that doesn't work
3. Pull repo (make sure nothing's missing) and do step 2

**Comment by tahanson-cisco** [comment] 2019-04-30 20:12
@anking - are you still facing the issue after @taymoork2's instructions?  If not are you able to reproduce this on a fresh installation?

**Comment by olivierproffit** [comment] 2019-06-27 20:54
@anking - we close this ticket but let us know if you still find some issue

**Closed by olivierproffit** 2019-06-27 20:54 UTC
